### ISSUE TITLE
Nothing built with ghc 7.6.3

### ISSUE THREAD

**Issue by bos** [lpsmith/bytestring-builder#1]
If I try to install this package with ghc 7.6.3 on my Mac, it builds nothing. Only if I manually edit the `bytestring_has_builder` flag in the `.cabal` file to `False` does anything actually happen. This is preventing me from being able to resolve https://github.com/bos/aeson/issues/177 and its associated fix, https://github.com/bos/aeson/pull/178 — please help.

**Comment by lpsmith** [comment]
Sure,  unfortunately I don't have access to a Mac,  but I will help as best I can.

Could you `cabal install groom` and then `cabal configure` with this [modified `Setup.hs`](https://gist.github.com/lpsmith/8837629),  piping the output to a file and sending me the result?    Hopefully I'll be able to deduce what's going on from that.

Also, what version of `Cabal` and `cabal-install` are you using?

**Comment by lpsmith** [comment]
Also, I don't know if there might be any slightly sensitive information in the output;  if you aren't comfortable posting it as a public gist,  you could create a private gist or email me the file.

**Comment by lpsmith** [comment]
Ok,  I did have somebody with a Mac run my debugging `Setup.hs`,  and it appears to have worked just fine,  and the bytestring-builder modules were indeed built.

Are you compiling against `bytestring-0.10.4`?   If so,  then `bytestring-builder` should be working as advertised.    The idea is that bytestring-builder isn't needed at that point, because bytestring already contains the added modules.   So any imports of those modules should normally resolve to the `bytestring` package.

**Comment by bos** [comment]
Hi, Leon –

I just emailed you a copy of the configure output. In it, you'll see that the standard bytestring 0.10.0.2 that comes with GHC 7.6.3 is the only version installed, and yet for some reason the Setup script believes that I have 0.10.4 or newer.

In case it could be relevant:

```
$ cabal --version
cabal-install version 1.19.2
using version 1.19.2 of the Cabal library
```

**Comment by lpsmith** [comment]
Yes, I'm pretty sure the problem is that you are using a newer version of `Cabal`,  that isn't populating the `configConstraints` in the same way it was before.   I should be able to replicate this on my own machine now,  and I will dig into it.

Thanks!

**Comment by lpsmith** [comment]
Ok,  I looked at this issue,  and it turns out that supporting the development version of Cabal without bumping up the lower cabal bound too much is quite an ugly problem. 

I think my only option is conditional compilation,  which is tricky as there isn't an usable CPP definition that specifies the version of Cabal being compiled against.   Carter pointed me to a [Template Haskell solution he cooked up](https://github.com/bos/llvm/blob/e1d1a700387400b1b668078befbc58c1c697202d/base/Setup.hs#L105-116),  but it sounds like quasiquotation is mostly out of the question because the quasiquoter needs the identifiers to resolve.    So it will be _especially_ ugly.

**Comment by lpsmith** [comment]
Ok, this issue appears to be fixed,   with the caveat that a fairly recent-ish version of cabal-install is now _required_.
