### ISSUE TITLE
`bytestring-builder` failures with GHC 7.2 and GHC 7.10

### ISSUE THREAD

**Issue by hvr** [lpsmith/bytestring-builder#4]
See https://ghc.haskell.org/~hvr/buildreports/bytestring-builder.html

```
src/Data/ByteString/Short/Internal.hs:139:10:
  No instance for (GHC.Generics.Generic ShortByteString)
  arising from a use of ‘Control.DeepSeq.$gdmrnf’
  In the expression: Control.DeepSeq.$gdmrnf
  In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
  In the instance declaration for ‘NFData ShortByteString’
```

**Comment by lpsmith** [comment]
Well,  I can't speak to the 7.2.2 failures much at all,   but cabal-install _should_ be compiling this as an empty package with 7.10

**Comment by lpsmith** [comment]
Actually,  doesn't GHC 7.10 ship with an as-of-yet unreleased version of bytestring?   bytestring-builder is pinned to a particular version of bytestring, see the commit comments for c1afc0b735ec3ac8a8fa224d5258881c95aab4f9.    So the only way this should actually come up with a build plan at all is if you are ignoring the version constraints,   which suggests that the hack introduced in #2 and  #3 is not working for this reason.

**Comment by lpsmith** [comment]
Honestly,  I don't really care about 7.2,  as is not packaged in any distribution repositories,  AFAIK,  and was never popular outside the academic part of the community,  so I seriously doubt very many people are continuing to use it.    Really,  I feel that issue is probably not mine to worry about anyway,  as I'm simply providing the packaging,  not the code,  and this is almost certainly a code issue.

The issue with 7.10 I'm unsure about the importance/practicality of.    On the one hand,  this will not be an issue once bytestring-0.10.6 is released and bytestring-builder-0.10.6 is released accordingly,   on the other hand it does demonstrate that the current build hack is a lot more fragile than one would prefer.

**Comment by hvr** [comment]
> On the one hand, this will not be an issue once bytestring-0.10.6 is released and bytestring-builder-0.10.6 is released accordingly

That's not entirely true, as `bytestring-builder-0.10.4.*` will still be available for build-plans to be picked. 

But I can try to devise a more robust fix for the `bytestring-builder-0.10.4.*` series if you're interested.

**Comment by lpsmith** [comment]
> That's not entirely true, as `bytestring-builder-0.10.4.*` will still be available for build-plans to be picked.

Isn't the problem in this case the fact that you are telling `cabal-install` to ignore the version constraints?

I suppose if I were to try to fix this myself,  I would go back to using the old `Setup.hs` magic,  if it can be adopted to the new `cabal-install`, without worrying about older versions of `cabal-install`.

In any case,  I would certainly be happy to adopt a better solution that you come up with.

**Comment by hvr** [comment]
> Isn't the problem in this case the fact that you are telling cabal-install to ignore the version constraints?

No, `cabal-install` in fact honors all constraints...
